#!/usr/bin/env python

import numpy as np
import ReadWrite as rw
import sys

fcol = int(sys.argv[2])-1
lcol = int(sys.argv[3])-1
try:
  h = int(sys.argv[-1])
  delta = 1
except:
  h = 0
  delta = 0

data_avg = []
data_tot = {}
print sys.argv
with open(sys.argv[1],"w") as fout:
  for f in range(len(sys.argv)-4-delta):
    data = rw.readFromColfile(sys.argv[f+4],header=h)
    data2 = rw.readFromColfile(sys.argv[f+4],header=h)
    data_tot[f] = data2[fcol:lcol+1][:][:]
    if (f==0):
      data_avg = data[fcol:lcol+1]
    elif (f>0):
      for c in range(fcol,lcol+1):
        for p in range(len(data_avg[0])):
          data_avg[c-fcol][p] = data_avg[c-fcol][p] + data[c][p]
  data_std = [[[data_tot[x][y][z] for x in range(len(sys.argv)-4-delta)] for y in range(len(data_avg))] for z in range(len(data_avg[0]))]
  for p in range(len(data_avg[0])):
    for c in range(len(data_avg)):
      fout.write("%f %f " %(float(data_avg[c][p])/(float(len(sys.argv)-4-delta)), np.std(data_std[p][c])))
    fout.write("\n")
