#!/usr/bin/env python

import sys
import PBC_RG as pbc
import ReadWrite as rw


if len(sys.argv)<3:
  print "Usage", sys.argv[0], "xyz filename Cell parameter filename"
  exit(1)

[Cell, Cell.C] = rw.readCell(sys.argv[2])
cart_pos = rw.readFromXYZFile(sys.argv[1])
red_pos = cart_pos[:]

nat = len(cart_pos[0])
nconf = len(cart_pos)

for t in range(nconf):
  for n in range(nat):
    r1 = pbc.get_coord(cart_pos[t][n])
    r2 = pbc.get_coord(red_pos[t][n])
    pbc.cart2red(r1,r2,Cell)
    red_pos[t][n] = pbc.make_point(r2[0],r2[1],r2[2],cart_pos[t][n].elt)

rw.writeTrajAsXYZFile(sys.argv[1].split(".xyz")[0]+"_red.xyz",red_pos)
