#!/usr/bin/env python

import sys
import ReadWrite as rw
import numpy as np

M = 5.4613e-21
name = sys.argv[1].split("/")[-1]
if ("zni" in name.split("_") or "ZNI" in name.split("_")):
  M = 5.4613e-21
elif ("zif4" in name.split("_") or "ZIF4" in name.split("_") or "ZIF-4" in name.split("_")):
  M = 5.4613e-21
elif ("zif8" in name.split("_") or "ZIF8" in name.split("_") or "ZIF-8" in name.split("_")):
  M = 4.7352e-21


ener = rw.readFromColfile(sys.argv[1]+".ener",header=20001)
kin = ener[2]
T = ener[3]
pot = ener[4]
U = [(kin[i]+pot[i]) for i in range(len(pot))]
U2 = [(kin[i]+pot[i])**2 for i in range(len(pot))]

Umoy = float(sum(U))/float(len(U))
U2moy = float(sum(U2))/float(len(U2))
Tmoy = float(sum(T))/float(len(T))
Tglob = Tmoy


Cv = (4.359744e-18)**2*(U2moy - Umoy**2)/(1.380648e-23*Tmoy**2*M)
print "#0 -", len(pot)/2000, "ps" , Tmoy, Cv, Umoy*4.359744e-18/M

period = 40 #period in ps
period2 = period #period2 in ps
split = period*2000 #translation to split
split2 = period2*2000
Cvlist=list()
for k in range(0,len(pot)-split,split2):
  #print k*split, (k+1)*split
  #print k
  U = [(kin[i]+pot[i]) for i in range(k,k+split)]
  U2 = [(kin[i]+pot[i])**2 for i in range(k,k+split)]
  T2 = [T[i] for i in range(k,k+split)]

  Umoy = float(sum(U))/float(len(U))
  U2moy = float(sum(U2))/float(len(U2))
  Tmoy = float(sum(T2))/float(len(T2))
  if (abs(Tmoy-Tglob)>0.02*Tglob):
    print "Too small window"
    print "Average T in this window is:", Tmoy, "compared to global average:", Tglob
    exit(1)


  Cv = (4.359744e-18)**2*(U2moy - Umoy**2)/(1.380648e-23*Tmoy**2*M)
  print k/2000, "-", (k+split)/2000, "ps" , Tmoy, Cv, Umoy*4.359744e-18/M
  Cvlist.append(Cv)

print "Average Cv = ", np.mean(Cvlist)
