#!/usr/bin/env python

import sys
import math
import numpy as np
import ReadWrite as rw
import PBC_RG as pbc

if (len(sys.argv)<4):
  print "Usage", sys.argv[0], "xyz basename ref_xyz basename cell parameters filename"
  exit(1)


xyz = sys.argv[1]
xyz_ref = sys.argv[2]

# Read the trajectory and the reference positions
trajPos = rw.readFromXYZFile(xyz + ".xyz",step=100)
refPos = rw.readFromXYZFile(xyz_ref+".xyz")[0]
[Cell, Cell.C] = rw.readCell(sys.argv[3])

nconf = len(trajPos)
nat = len(refPos)
Used = pbc.get_elements(refPos)
#print nat, Used

Out = xyz.split("/")[-1]

Deltas = [0.0 for y in range(nconf)]
for t in range(nconf):
  diff = [0.0 for x in range(nat)]
  for n in range(nat):
    post = pbc.get_coord(trajPos[t][n])
    pos0 = pbc.get_coord(refPos[n])
    diff[n] = pbc.distance_cart(post,pos0,Cell)
    Deltas[t] = Deltas[t]+diff[n]**2
  print t, Deltas[t]/nat
