#!/usr/bin/env python

import numpy as np
import sys, os
import ReadWrite as rw
from pymatgen import Lattice, Structure, Molecule
from pymatgen.io.cif import CifParser
from pymatgen.io.xyz import XYZ

parser = CifParser(sys.argv[1])
structure = parser.get_structures()[0]
mol = Molecule(structure.species,structure.cart_coords)
name = sys.argv[1].split(".")[0]+".xyz"
mol.to(filename=name)

os.system('cfiles angles '+name+' -s "dihedrals: name(#1) Si and name(#2) O and name(#3) Si and name(#4) O" --guess-bonds -o '+name.split(".")[0]+".dihe")
SiOSiO = rw.readFromColfile(name.split(".")[0]+".dihe",header=2)
a=[SiOSiO[0][i]*SiOSiO[1][i] for i in range(len(SiOSiO[0]))]
SiOSiO_mean = np.sum(a)/(np.sum(SiOSiO[1]))
#print SiOSi_mean

os.system('cfiles angles '+name+' -s "angles: name(#1) Si and name(#2) O and name(#3) Si" --guess-bonds -o '+name.split(".")[0]+".angle")
SiOSi = rw.readFromColfile(name.split(".")[0]+".angle",header=2)
a=[SiOSi[0][i]*SiOSi[1][i] for i in range(len(SiOSi[0]))]
SiOSi_mean = np.sum(a)/(np.sum(SiOSi[1]))
#print SiOSi_mean

os.system('cfiles rdf '+name+' -s "pairs: name(#1) Si and name(#2) O" --max=3.0 -o '+name.split(".")[0]+".rdf")
SiO = rw.readFromColfile(name.split(".")[0]+".rdf",header=3)
a=[SiO[0][i]*SiO[1][i] for i in range(len(SiO[0]))]
SiO_mean = np.sum(a)/(np.sum(SiO[1]))
#print SiO_mean

print name.split(".")[0], SiO_mean, SiOSi_mean, SiOSiO_mean
