#!/usr/bin/env python

import sys

cl = 0
Utmp = 0
with open(sys.argv[1],"r") as fin:
  with open(sys.argv[1]+"U2",'w') as fout:
    for line in fin:
      if (cl==0): 
        Utmp = float(line.split()[2])
        Ttmp = float(line.split()[0])
      U = float(line.split()[2])
      T = float(line.split()[0])
      if (cl>0):
        DU = (U-Utmp)/(T-Ttmp)
        fout.write(str((T+Ttmp)/2)+" "+str(DU)+"\n")
      Utmp = U
      Ttmp = T
      cl = cl+1
