#!/usr/bin/env python

import numpy as np
import sys
import ReadWrite as rw
from pymatgen import Lattice, Structure, Molecule
from pymatgen.io.xyz import XYZ
import imp
from types import ModuleType
c2r = ModuleType("Cart2Red")
data = open("/home/gaillac/.local/bin/PhD_scripts/Cart2Red").read()
exec data in c2r.__dict__

dt = 0.5
if (len(sys.argv)>3): dt = float(sys.argv[3])

step = int(1000*float(0.5/dt))
Traj = rw.readFromXYZFile(sys.argv[1],step=step)
nconf = len(Traj)

[Cell, Cell.C] = rw.readCell(sys.argv[2])
lattice = Lattice.from_parameters(a=Cell.a, b=Cell.b, c=Cell.c, alpha=Cell.alpha*180.0/np.pi,beta=Cell.beta*180.0/np.pi, gamma=Cell.gamma*180.0/np.pi)
for t in range(0,nconf):
  name = sys.argv[1].split(".xyz")[0]+"_%06d.xyz" %(t*step)
  rw.writeTrajAsXYZFile(name,[Traj[t]])

  xyz = Molecule.from_file(name)

  struct = Structure(lattice,xyz.species,c2r.CartPos2Red(Cell,[xyz.cart_coords])[0])

  struct.to(filename=name.split(".xyz")[0]+".cif")
